const express = require('express');
const pool = require('../db');
const { verifyToken, requireRole } = require('../middleware/auth');
const { getCoordinatorUnitId } = require('../utils/unitAccess');

const router = express.Router();

const OLLAMA_URL = process.env.OLLAMA_URL || 'http://localhost:11434/api/chat';
const OLLAMA_MODEL = process.env.OLLAMA_MODEL || 'qwen2.5:7b';

// Tells the model what Sessioneer is and how to behave. Sent as the first
// message on every request so it never forgets its role mid-conversation.
const SYSTEM_PROMPT = `You are the assistant built into Sessioneer, a system that helps Unit Coordinators (UCs) manage tutor scheduling.

Things a UC can do in this system:
- Sessions / Schedule Builder: create and edit sessions, build the timetable
- Availability: view the availability tutors have submitted
- Requests: handle tutor swap / leave / cover requests
- Applications: review tutor applications
- Messages: group or direct chat with tutors

Rules:
- If the user asks "how do I..." or "where is...", call the explain_feature tool. Never invent a feature or button that doesn't exist.
- If the user wants to look something up (e.g. who hasn't submitted availability), call the list_unsubmitted_tutors tool.
- If the user describes a situation but hasn't given enough detail (e.g. which session, which unit), ask a short follow-up question instead of guessing.
- Keep replies short and casual, like a colleague answering quickly - not a long essay.
- Reply in the same language the user wrote in.`;

// ---- FAQ answers (written by hand, not generated by the model - keeps them
// accurate instead of letting the model invent buttons that don't exist) ----
const FEATURE_GUIDE = {
  request_cover: 'Go to the Requests page in the left nav, click "Request Cover", pick the session that needs covering, and send it.',
  create_session: 'Go to Schedule Builder, click "+ Add Session", and fill in the time, location, and headcount.',
  submit_availability: 'Go to the Availability page, click each time slot to cycle Preferred / Available / Avoid, then click Submit when done.',
  invite_tutor: 'Go to Applications - you can send an invite link directly, or review applications tutors submitted themselves.',
  view_schedule: 'Go to the Schedule page to see the current timetable.'
};

// ---- Tools the bot is allowed to call ----
const tools = [
  {
    type: 'function',
    function: {
      name: 'explain_feature',
      description: 'Call this when the user asks where a feature is or how to use it, e.g. "where do I request cover"',
      parameters: {
        type: 'object',
        properties: {
          topic: {
            type: 'string',
            enum: Object.keys(FEATURE_GUIDE),
            description: 'The feature the user is asking about'
          }
        },
        required: ['topic']
      }
    }
  },
  {
    type: 'function',
    function: {
      name: 'list_unsubmitted_tutors',
      description: 'Look up which tutors on a unit have not submitted their availability yet',
      parameters: {
        type: 'object',
        properties: {
          unitCode: { type: 'string', description: 'Unit code, e.g. CAB201' }
        },
        required: ['unitCode']
      }
    }
  }
];

const explainFeature = (topic) => ({
  answer: FEATURE_GUIDE[topic] || "I'm not sure about that one - try looking in the left nav, or check with an admin."
});

const listUnsubmittedTutors = async (unitCode, coordinatorId) => {
  const unitResult = await pool.query(
    'SELECT id FROM units WHERE unit_code = $1 LIMIT 1',
    [unitCode]
  );
  const unit = unitResult.rows[0];
  if (!unit) return { error: `Couldn't find a unit called "${unitCode}"` };

  const ownedUnitId = await getCoordinatorUnitId(unit.id, coordinatorId);
  if (!ownedUnitId) return { error: `You're not the coordinator for ${unitCode}, so you can't view this.` };

  const result = await pool.query(
    `
    SELECT TRIM(CONCAT(u.name, ' ', COALESCE(u.last_name, ''))) AS name
    FROM users u
    JOIN unit_memberships um
      ON um.user_id = u.id AND um.unit_id = $1 AND um.role IN ('tutor', 'super_tutor')
    LEFT JOIN (
      SELECT DISTINCT tutor_id FROM availability WHERE is_submitted = TRUE
    ) sub ON sub.tutor_id = u.id
    WHERE sub.tutor_id IS NULL
    ORDER BY name
    `,
    [unit.id]
  );

  return { unitCode, unsubmittedTutors: result.rows.map(r => r.name) };
};

const executeTool = async (name, args, req) => {
  if (name === 'explain_feature') return explainFeature(args.topic);
  if (name === 'list_unsubmitted_tutors') return listUnsubmittedTutors(args.unitCode, req.user.id);
  return { error: `Unknown tool: ${name}` };
};

// POST /bot/chat
// Body: { message: "...", history: [{ role: 'user'|'assistant', content: '...' }, ...] }
// `history` is the past turns of THIS conversation, sent by the frontend each
// time - Ollama itself has no memory between requests, so we resend it.
router.post('/chat', verifyToken, requireRole('coordinator'), async (req, res) => {
  try {
    const { message, history = [] } = req.body;
    if (!message || !message.trim()) {
      return res.status(400).json({ error: 'message is required' });
    }

    const messages = [
      { role: 'system', content: SYSTEM_PROMPT },
      ...history,
      { role: 'user', content: message }
    ];

    const ollamaRes = await fetch(OLLAMA_URL, {
      method: 'POST',
      body: JSON.stringify({
        model: OLLAMA_MODEL,
        messages,
        tools,
        stream: false
      })
    });

    if (!ollamaRes.ok) {
      return res.status(502).json({ error: 'Bot is unavailable right now - is Ollama running?' });
    }

    const data = await ollamaRes.json();
    const msg = data.message;

    if (msg.tool_calls && msg.tool_calls.length > 0) {
      const call = msg.tool_calls[0];
      const result = await executeTool(call.function.name, call.function.arguments, req);
      // Turn the raw tool result into a short natural-language reply so the
      // widget always shows plain text, not a JSON blob.
      const reply = result.error
        ? result.error
        : (result.answer || (result.unsubmittedTutors
            ? (result.unsubmittedTutors.length
                ? `Tutors on ${result.unitCode} who haven't submitted availability: ${result.unsubmittedTutors.join(', ')}`
                : `Everyone on ${result.unitCode} has submitted their availability.`)
            : JSON.stringify(result)));
      return res.json({ reply });
    }

    return res.json({ reply: msg.content });
  } catch (error) {
    console.error('Bot chat error:', error);
    res.status(500).json({ error: 'Something went wrong on the bot side' });
  }
});

module.exports = router;